S07_Activity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path('admin/', admin.site.urls),
]

django_practice/urls.py
from django.urls import path
from . import views

app_name = 'django_practice'
urlpatterns = [
	path('', views.index,name= 'index'),
	path('register',views.register, name='register'),
	path('change_password',views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_item', views.add_item, name="add_item"),
	path('<int:groceryitem_id>/', views.groceryitem, name = 'viewgroceryitem'),
	path('<int:groceryitem_id>/edit', views.update_item, name='update_item'),
	path('<int:groceryitem_id>/delete', views.delete_item, name='delete_item'),

]

django_practice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class GroceryItem(models.Model):
	item_name =  models.CharField(max_length=50)
	category = models.CharField(max_length=50)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete = models.CASCADE, default ="")

django_practice/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddItemForm(forms.Form):
	item_name = forms.CharField(label='Item Name', max_length=50)
	category = forms.CharField(label='Category', max_length=200)

class UpdateItemForm(forms.Form):
	item_name = forms.CharField(label='Item Name', max_length=50)
	category = forms.CharField(label='Category', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	email = forms.CharField(label='Email', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

django_practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout
from django.forms.models import model_to_dict
from django.utils import timezone
# Create your views here.

from .models import GroceryItem
from .forms import LoginForm, AddItemForm, UpdateItemForm, RegisterForm


def index(request):
	groceryitem_list = GroceryItem.objects.filter(user_id = request.user.id)
	context = {
		'groceryitem_list': groceryitem_list,
		'user': request.user
	}
	return render(request, "django_practice/index.html",context)

def groceryitem(request,groceryitem_id):
	groceryitem = get_object_or_404(GroceryItem,pk=groceryitem_id)

	return render (request, "django_practice/groceryitem.html", model_to_dict(groceryitem))


def register(request):
	
	context = {}
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid() == False:
			form = RegisterForm()
		else:
			user = User()
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			is_staff = False
			is_active = True 

			# user = authenticate(username=username, password=password)
			# print(user)
			# if user is None:
			# 	authenticated_user = User(username = username)
			# 	authenticated_user.set_password(password)
			# 	authenticated_user.save()

			

			duplicates = User.objects.filter(username = username)

			if not duplicates:
				
				User.objects.create(username = username, first_name = first_name, last_name = last_name, email = email, is_staff = is_staff , is_active = is_active , password = password)

				
				return redirect("django_practice:login")
			else:
				context = {
					"error": True
				}
	return render(request, "django_practice/register.html", context)


def change_password(request):
	is_user_authenticated = False

	user = authenticate(username="alexbuena", password="alexa1")
	print(user)

	if user is None:
		authenticated_user = User.objects.get(username="johndoe")
		authenticated_user.set_password('johndoe1')
		authenticated_user.save()
		is_user_authenticated = True

	context = {
		"is_user_authenticated": is_user_authenticated
	}

	return render(request, "django_practice/change_password.html", context)

def login_view(request):
	context = {}
	
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid() == False:
			form = LoginForm()
		else:

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			# authenticated_user = User(username = username)
			# authenticated_user.set_password(password)
			# authenticated_user.save()
			user = authenticate(username=username, password=password)
			print(user)
				
			context = {
				"username": username,
				"password": password
			}
	
			if user is not None:
				login(request,user)
				return redirect("django_practice:index")
			else:
				context = {
					"error": True
				}
	return render(request, "django_practice/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("django_practice:login")

def add_item(request):
	context = {}
	if request.method == 'POST':
		form = AddItemForm(request.POST)
		if form.is_valid() == False:
			form = AddItemForm()
		else:
			item_name = form.cleaned_data['item_name']
			category = form.cleaned_data['category']

			duplicates = GroceryItem.objects.filter(item_name = item_name)

			if not duplicates:
				GroceryItem.objects.create(item_name = item_name, category = category, date_created = timezone.now(),user_id=request.user.id)
				return redirect("django_practice:index")
			else:
				context = {
					"error": True
				}
	return render(request, "django_practice/add_item.html", context)

def update_item(request, groceryitem_id):
	groceryitem = GroceryItem.objects.filter(pk=groceryitem_id)

	context ={
		"user": request.user,
		"groceryitem_id": groceryitem_id,
		"item_name": groceryitem[0].item_name,
		"category": groceryitem[0].category,
		"status": groceryitem[0].status
	}
	if request.method == 'POST':
		form = UpdateItemForm(request.POST)
		if form.is_valid() == False:
			form = UpdateItemForm()
		else:
			item_name = form.cleaned_data['item_name']
			category = form.cleaned_data['category']
			status = form.cleaned_data['status']

			if groceryitem:
				groceryitem[0].item_name = item_name
				groceryitem[0].category = category
				groceryitem[0].status = status

				groceryitem[0].save()
				return redirect("django_practice:index")

			else:
				context ={
					"error": True
				}
	return render(request, "django_practice/update_item.html", context)

def delete_item(request, groceryitem_id):
	groceryitem = GroceryItem.objects.filter(pk=groceryitem_id).delete()
	return redirect("django_practice:index")

django_practice/templates/django_practice/add_item.html
{% extends 'base.html' %}
{% block title %}Add Item{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add an Item</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate item found</p>
				{% endif %}
				<form action="{% url 'django_practice:add_item' %}" method="post">
				{% csrf_token %}

					<div class="mb-3">
						<label for="item_name">Item Name:</label>
						<input class="form-control" id="item_name" type="text" name="item_name" value="{{ item_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="category">Category:</label>
						<textarea class="form-control" name="category" value="{{ category }}"required></textarea>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Add Item">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

django_practice/templates/django_practice/change_password.html
{% if is_user_authenticated == False %}
	<h1> Invalid User Credentials</h1>
	<p>Check if the username and password is correct.</p>
{% else %}
	<h1>User Password Successfully Updated</h1>
	<p> Th password has been successfully updated</p>

{% endif %}

django_practice/templates/django_practice/groceryitem.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="text-center my-3">
	<h1>{{ item_name }}</h1>
	<h3>Category</h3>
	<p>{{ category }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:update_item' id %}" class="text-light text-decoration-none">Edit Item</a>
	</button>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:delete_item' id %}" class="text-light text-decoration-none">Delete Item</a>
	</button>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:index' %}" class="text-light text-decoration-none">Back to Grocery List</a>
	</button>
</div>


{% endblock %}

django_practice/templates/django_practice/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
	{% if groceryitem_list and user.is_anonymous == False %}
		<h1 class="text-center my-3">Welcome {{ user.first_name }} {{ user.last_name }}!</h1>
		<div class="container">
			<div class="row">
				<h3 class="text-center mb-3">My Grocery Item</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
				{% for groceryitem in groceryitem_list %}
					<li class="list-group-item">
						<a href="{% url 'django_practice:viewgroceryitem' groceryitem.id %}" class="text-decoration-none">   {{ forloop.counter }} {{groceryitem.item_name}}</a>
					</li>
					<br>
				{% endfor %}
				</ul>
			</div>
		</div>
	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page </h1>
		<p class= "text-center">Kindly Login<a href="{% url 'django_practice:login' %}"> here</a></p>
	{% else %}
		<p> No items have been created</p>
		
	{% endif %}
{% endblock %}

django_practice/templates/django_practice/login.html
{% extends 'base1.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and password</p>
			{% endif %}	
			<form action="{% url 'django_practice:login' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="password">Password</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Login">
				</div>
			</form>
			<br><br>
			<div class="text-end">
					<h5 class= "text-end">Dont have an account? <a class="btn btn-outline-dark" href="{% url 'django_practice:register' %}">Register here</a></h5>
					
			</div>

		</div>
	</div>
</div>
{% endblock %}

django_practice/templates/django_practice/register.html
{% extends 'base1.html' %}
{% block title %}Register{% endblock %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if error == True %}
				<p class="text-danger">User Already Registered</p>
			{% endif %}	
			<form action="{% url 'django_practice:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username:</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="first_name">First Name:</label>
					<input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="last_name">Last Name:</label>
					<input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="email">Email:</label>
					<input class="form-control" id="email" type="text" name="email" value="{{ email }}" maxlength="30" required>
				</div>

				<div class="mb-3">
					<label for="password">Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="30" required>
				</div>

				<!-- <div class="mb-3">
					<label for="password">Confirm Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="30" required>
				</div> -->

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Register">
				</div>

			</form>
			<br><br>
			<div class="text-end">
					<h5 class= "text-end">Already have an account? <a class="btn btn-outline-dark" href="{% url 'django_practice:login' %}">Login here</a></h5>
					
		</div>
	</div>
</div>
{% endblock %}

django_practice/templates/django_practice/update_item.html
{% extends 'base.html' %}
{% block title %}Update Item{% endblock %}
{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Item</h1>
				{% if error == True %}
					<p class="text-danger">Item not found</p>
				{% endif %}	
				<form action="{% url 'django_practice:update_item' groceryitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="item_name">Item Name:</label>
						<input class="form-control" id="item_name" type="text" name="item_name" value="{{ item_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="category">Category:</label>
						<textarea class="form-control" name="category" value="{{ category }}"required></textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status:</label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Update Item">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to enter this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'django_practice:login' %}"> here</p>
	{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}Grocery Item App{% endblock %} </title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	{% include "navbar.html" %}
	{% block content %}
	{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/base1.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}Grocery Item App{% endblock %} </title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	{% block content %}
	{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'django_practice:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'django_practice:add_item' %}">Add Grocery Item</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'django_practice:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>